name: build and test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with: 
          starknet-foundry-version: 0.32.0

      - uses: actions/checkout@v3
      
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.4"

      - name: Set environment variables
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: |
          echo "MAINNET_RPC_URL is set"
      
      - name: Export environment variables
        run: |
          echo "MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }}" >> $GITHUB_ENV
          export MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }}

      - run: scarb fmt --check

      - uses: foundry-rs/setup-snfoundry@v3
        with: 
          starknet-foundry-version: 0.32.0
      
      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: error
          retry_wait_seconds: 60
          command: snforge test --max-n-steps 30000000 --rerun-failed